### ISSUE TITLE
Ch: 5 - Endless babel errors

### ISSUE THREAD

**Issue by wisefool** [MoonHighway/learning-react#47]
Using the instructions in Ch 5 to install webpack and babel result in errors and nothing will work.

`$ npm install babel-core babel-loader babel-preset-env babel-preset-react babel-preset-stage-0 --save-dev`

Results in:

```npm WARN saveError ENOENT: no such file or directory, open '/Users/username/projects/learning-react/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/username/projects/learning-react/package.json'
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.6 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN learning-react No description
npm WARN learning-react No repository field.
npm WARN learning-react No README data
npm WARN learning-react No license field.


+ babel-preset-stage-0@6.24.1
+ babel-preset-react@6.24.1
+ babel-loader@8.0.6
+ babel-preset-env@1.7.0
+ babel-core@6.26.3
added 154 packages from 68 contributors and audited 2879 packages in 10.018s
found 0 vulnerabilities
```

Then running `$ npm install react react-dom --save`

Returns this:
```npm WARN saveError ENOENT: no such file or directory, open '/Users/username/projects/learning-react/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/username/projects/learning-react/package.json'
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.6 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN learning-react No description
npm WARN learning-react No repository field.
npm WARN learning-react No README data
npm WARN learning-react No license field.

+ react-dom@16.8.6
+ react@16.8.6
added 6 packages from 1 contributor and audited 8785 packages in 1.544s
found 0 vulnerabilities
```

So it installs something but still gives errors. Then I created webpack.config.js and when I run `webpack` I get:

```Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "dist/assets" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

So I changed that value to an absolute path and I get this:

```/usr/local/lib/node_modules/webpack/lib/RuleSet.js:264
			throw new Error(
			^

Error: options/query cannot be used with loaders (use options for each array item) in {
  "test": {},
  "exclude": {},
  "loader": [
    "babel-loader"
  ],
  "query": {
    "presets": [
      "env",
      "stage-0",
      "react"
    ]
  }
}
    at Function.normalizeRule (/usr/local/lib/node_modules/webpack/lib/RuleSet.js:264:10)
    at rules.map (/usr/local/lib/node_modules/webpack/lib/RuleSet.js:110:20)
    at Array.map (<anonymous>)
    at Function.normalizeRules (/usr/local/lib/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/usr/local/lib/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/usr/local/lib/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/usr/local/lib/node_modules/webpack/lib/Compiler.js:586:31)
    at Compiler.newCompilationParams (/usr/local/lib/node_modules/webpack/lib/Compiler.js:603:30)
    at Compiler.compile (/usr/local/lib/node_modules/webpack/lib/Compiler.js:611:23)
    at readRecords.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:284:11)
    at Compiler.readRecords (/usr/local/lib/node_modules/webpack/lib/Compiler.js:479:11)
    at hooks.run.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:281:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:278:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/usr/local/lib/node_modules/webpack/lib/Compiler.js:275:24)
    at processOptions (/usr/local/lib/node_modules/webpack-cli/bin/cli.js:352:14)
    at yargs.parse (/usr/local/lib/node_modules/webpack-cli/bin/cli.js:363:3)
    at Object.parse (/usr/local/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /usr/local/lib/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
```

Researching this error gives me a lot of pages suggesting how to fix babel 6 vs 7 issues and everything I've tried is a rabbit hole that doesn't fix anything.

**Comment by deeprave** [comment]
I believe the problem here is that React has moved on from the version used in this book.

React v16.8+ brought quite a few changes, and babel has moved on too (e.g. babel-core is now @babel/core etc.). Either you need to move back to pre-16.8 react, or this book needs updating (which I think is the correct answer). React now has hooks and nobody uses component classes anymore, same for Redux also.

To get a working react/babel/webpack environment i would suggest create-react-app https://reactjs.org/docs/create-a-new-react-app.html as a starting point. It obfuscates a lot under the cover (you can "eject" to fix that if you're curious), but it is a fast way to  get working with contemporary versions and tooling.

**Comment by MWolman1990** [comment]
This is still an on-going problem that I'm working on myself. I'm not going to take the time to list out all of my code and files. I'll just say that babel and webpack have changed so significantly from the time this book was written that the webpack/babel parts to this chapter are completely outdated and only serve as a catalyst to push guys like me into a much further deeper understanding of webpack/babel. So, in the end, I am grateful, because I've learned a lot, but so far I'm 6 hours deep on the same problem, literally not moving forward a single page in the textbook. Disappointing overall, but I understand it's not your fault.

**Comment by jordanpapaleo** [comment]
@MWolman1990 Welcome to the wonderful world of JavaScript engineering :). We have all been where you are and there is no book that is completely fool proof with the ever-changing landscape of JavaScript.  You will encounter this scenario every day for the rest of your career in software.  I am glad to see you are learning how to work through these bumps.  It will make you better.

No author can protect its readers 100%.  Eve and Alex try really hard despite this crazy JavaScript environment because they truly want to see you learn.  Please remember that next time you feel the need to call hundreds of hours of work disappointing.

Feel free to hit me up https://beers-slack-invite.herokuapp.com if you want some help with the babel 6 to 7 port.  I have done it a few times too many ;)

**Comment by MWolman1990** [comment]
@jordanpapaleo thank you for your kind response and I completely understand what you're saying. At this point it, as far as I know, it would be impossible for a textbook to stay 100% up to date on this stuff. So yeah, I totally get it. My frustration is personal, nothing more.

I appreciate the offer. I can't tell at this point if porting babel from 6 to 7 is going to be what I need to solve my problem. I'm too deep into the research with my current knowledge level to even know where I'm wrong at this point. I'm just going to move on and come back to it later but probably just follow a different tutorial if I really feel the need to know how to resolve this.

**Comment by eveporcello** [comment]
Hey @MWolman1990. Thanks for the message. I totally understand the frustration. Are you working with the Second Edition of the book? The one with the color cover? If so, our Babel instructions should be more up to date there. If you send me your email address, I can send you the new one if you'd like. You're welcome to send me an email at `eve@moonhighway.com` too if there's something I can help debug.

(And thanks @jordanpapaleo. You're a GitHub/friend MVP!)

**Comment by MWolman1990** [comment]
Hey @eveporcello. Thank you for your offers! I did happen to come across the second edition of the book and I am interested. I'll email you.

If I made a repo with my project could you guys look at it and see if you can tell where I'm wrong?

**Comment by eveporcello** [comment]
absolutely! Send it over!
